name: ci
on:
    pull_request:
        branches:
            - '*'
    push:
        branches:
            - '*'
jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 'latest'

            - name: Install bun dependencies
              run: bun install

            - name: Run ESLint
              run: bun run lint
